### ISSUE TITLE
Unintentional Breaking Change

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/core#35]
# Overview
PR #31 unintentionally created a breaking change to the way that drivers work. Adding a property or method to a stream returned by a driver will be lost because [here](https://github.com/motorcyclejs/core/blob/develop/src/index.js#L17-L19) the stream is transformed with `.until()`, which returns a new stream without any properties or methods that are previously set.

# Discussion
I'd like to discuss whether or not this should be reverted.

###### Pros

- No mutation of streams
- Requires more thinking about the API for a driver
- Easily avoided by returning an object with methods
- Sinks, and not just sinkProxies, can be disposed of directly.

###### Cons

- Requires more thinking about the API for a driver
- Possibly unexpected behaviour for someone writing a driver
- Adds complexity to *core*
- Makes transitioning from Cycle to Motorcycle more difficult

On another note, if simply returning the stream *without* tacking `.until()` onto it, sinkProxies can still be disposed of, still keeping further values from reaching the application, but this [test](https://github.com/motorcyclejs/core/blob/develop/test/index.js#L127-L143) will need to be removed.

**UPDATE** : The test actually continues to pass with this 'feature' removed.

# References
Proof of the breaking change : https://github.com/motorcyclejs/html/commit/da8907376b684fbd9cf174b3ff8849a4cd37f68f (Keeping/changing that API is another discussion)

This will also effect isolate() support of the HTTP driver in it's current form. https://github.com/motorcyclejs/http/blob/develop/src/index.js#L150-L151

**Comment by TylorS** [comment]
I'm currently in favour of removing this 'feature', and the related test. On the grounds of complexity and ease of transition from Cycle to Motorcycle. From an technical standpoint nothing really changes, except the test cannot continue to work. As it stands, `sinkProxies` gets fed into `sources` which in turn gets fed into the `sinks` and back to `sinkProxies`. If this is reverted, `sources` and `sinkProxies` can still be terminated by `dispose()`, killing the loop. However, any values `sinks` still holds will be played out and the stream should complete.

@staltz @Frikki I really need feedback on this. It's not a decision I want to make on my own.

**Comment by TylorS** [comment]
Even at best, only **some** `sinks` can be disposed of, as it stands.

**Comment by TylorS** [comment]
It could also be possible to re-add any non-most.Stream methods and properties back to the new Stream. Maybe something like:
```js
const callDrivers = (drivers, sinkProxies, disposableStream) =>
  Object.keys(drivers)
    .reduce((sources, driverName) => {
      const source =
        drivers[driverName](hold(sinkProxies[driverName].stream), driverName)



      sources[driverName] = typeof source.until === `function` ?
          source.until(disposableStream) :
          source

      return sources
    }, {})
```

**Comment by Frikki** [comment]
What 'feature' are you referring to? Is it a new feature that was added. Is it an existing feature that comes from Cycle.js? Is the addition of 'until()' on a stream what you call a 'feature'?

Then initially, under *Discussion*, what are these pro/cons for? The revert? Also, 'Requires more thinking about the API for a driver' appears in both lists.

**Comment by TylorS** [comment]
Sorry, I thought I was clear. The 'feature' I'm referring to is the ability to directly dispose of *sinks* returned by `run()` caused by the code here: https://github.com/motorcyclejs/core/blob/develop/src/index.js#L17-L19. So yes, the addition of `until()`.

Under *Discussion*, the pros and cons were for keeping the 'feature'.  'Requires more thinking about the API for a driver'  could be a good thing or a bad thing, depending on your point of view.

**Comment by Frikki** [comment]
So should I merge #36 ?

**Comment by TylorS** [comment]
I'm leaning towards yes, I think that it makes sense, as the tests continue to pass, and it makes everything work as, I would think, a developer would expect.

**Comment by Frikki** [comment]
If we keep this functionality, if a developer needs to add a new property/method to the stream, couldn’t he just clone it first, or perform an operation that returns a new stream, and *then* add properties/methods?

**Comment by TylorS** [comment]
What do you mean by 'just clone it first'? By 'perform an operation that returns a new stream', you mean like how the DOM driver returns an object with methods that *then* return streams?

**Comment by Frikki** [comment]
> Adding a property or method to a stream returned by a driver will be lost because here the stream is transformed with .until(), which returns a new stream without any properties or methods that are previously set.

I am talking about cloning the stream first, or perform an operation on it that returns a new stream, which the developer *then* can add properties/methods to. And my question is if that would be possible?

**Comment by TylorS** [comment]
No, I don't believe that to be possible. If **any** stream is returned with any addition properties or methods not on `most.Stream.prototype`, they will be lost.

**Comment by Frikki** [comment]
Keeping the functionality leads to this options then:

- If you need additional properties/methods on a stream returned by a driver, fork the driver and make your own version with your requirements.

This is quite consistent with how compiled code works in other languages.

**Comment by TylorS** [comment]
No, I mean inside of the driver, like [here](https://github.com/motorcyclejs/http/blob/develop/src/index.js#L150-L151).
By the time it gets to the user isolateSink and isolateSource are not accessible.

**Comment by Frikki** [comment]
Why is my comment right above invalid? I don’t understand.

**Comment by TylorS** [comment]
I think it is **I** who don't understand :worried:

**Comment by Frikki** [comment]
No, I am confused now :|

**Comment by Frikki** [comment]
Please provide a minimal example code of what **cannot** be done with this 'feature' in place.

**Comment by TylorS** [comment]
```js
import {run} from '@motorcycle/core

const main = sources => ({
  other: sources.other.hello('Frederick').startWith('Motorcycle')
})

const driver = sink$ => {
  const source$ = sink$
  source$.hello = name => sink$.tap(() => {
    console.log(`Hello, from ${name}`)
  })
  return source$
}

run(main, {other: driver})
```

This will throw an error `hello is not defined` or very similar.

**Comment by Frikki** [comment]
Will this error be thrown in `main` or the driver?

**Comment by TylorS** [comment]
In `main`.

**Comment by TylorS** [comment]
Where hello() is attempting to be invoked.

**Comment by TylorS** [comment]
So the driver gets call with a sink proxy
```js
sources['other'] = drivers['other'](sinkProxes['other'].stream, 'other').until(disposableStream)
```
The `.until()` is where it get ruined.
It's the equivalent of calling, roughly
```js
sources['until'] = new UntilStream(drivers['other'](sinkProxies['other'].stream, 'other'))
sources['until'].hello // doesnt exist
sources['until].source.hello // does exist
```

**Comment by Frikki** [comment]
But!!! That’s terrible. How can the DOM driver work then?!?

**Comment by Frikki** [comment]
I think I’m at the point where I don’t want this 'feature'.

**Comment by TylorS** [comment]
The DOM Driver still works because it returns an object not a stream. This only affects streams that are returned directly, which isn't uncommon.

There is a check
```js
const source = drivers['other'](sinkProxies['other'].stream, 'other')

return typeof source.until === 'function' ? source.until(disposableStream) : source
```

**Comment by Frikki** [comment]
Returning a stream is the norm. The DOM driver is an exception.

**Comment by TylorS** [comment]
Exactly.

**Comment by Frikki** [comment]
But then, how often would you add methods/properties to a stream in a driver?

**Comment by TylorS** [comment]
Anytime you want to add support for `isolate()`

**Comment by Frikki** [comment]
Ugh!!! This 'feature' needs to go ASAP!!!

**Comment by TylorS** [comment]
So merge #36?

**Comment by Frikki** [comment]
The only *real benefit* it brings is disposing of sinks directly, correct?

**Comment by Frikki** [comment]
And what is the benefit of disposing sinks directly?

**Comment by TylorS** [comment]
It happens faster? Haha I can't really think of any. It was just easy to implement and passed core's tests.

**Comment by Frikki** [comment]
Well, that settles it, doesn’t it?

**Comment by TylorS** [comment]
I think so. The funny thing is the test I wrote **for** this 'feature' still passes without it.

**Comment by Frikki** [comment]
That’s what you get from not doing TDD.

**Comment by TylorS** [comment]
Erik Meijer made me do it! :wink:

**Comment by Frikki** [comment]
Only Erik Meijer can do without TDD.

**Comment by Frikki** [comment]
Anyway, so we merge #36 , yeah?

**Comment by TylorS** [comment]
Yes :+1:
